name = "Teched Up"
author = "Tomodachi94"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85332bce8aa56b7399d13adcf8a72eafb196e1d662c279215a004c41a77f0157"

[versions]
forge = "9.11.1.965"
minecraft = "1.6.4"

[options]
acceptable-game-versions = ["1.6.2", "CB 1.6.4-R2.0"]
