name = "Teched Up"
author = "Tomodachi94"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65069cbbf0f2941be9be8c7a84cbd593c40dd429c91d139a0fef521fe0c99243"

[versions]
forge = "9.11.1.965"
minecraft = "1.6.4"

[options]
acceptable-game-versions = ["1.6.2", "CB 1.6.4-R2.0"]
